[package]
name = "model_handler"
version = "0.1.0"
edition = "2024"

[lib]
name = "model_handler"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = "1.0"
indexmap = "2.7"
either = "1.13"
candle-core = { version = "0.9.1", features = ["metal"] }
candle-transformers = { version = "0.9.1", features = ["metal"] }
candle-nn = { version = "0.9.1" }
tokenizers = "0.22.2"